FROM node:14-alpine as dependencies
WORKDIR /app
COPY package.json next-env.d.ts next-i18next.config.js \
 next.config.js postcss.config.js tailwind.config.js tsconfig.json vercel.json ./
RUN yarn install --frozen-lockfile

FROM node:14-alpine as builder
WORKDIR /app
ARG NEXT_PUBLIC_API_ENDPOINT
ARG APPLICATION_MODE
ARG NEXT_PUBLIC_ADMIN_URL
ARG NEXT_PUBLIC_DEFAULT_LANGUAGE
ARG NEXT_PUBLIC_ENABLE_MULTI_LANG
ARG NEXT_PUBLIC_AVAILABLE_LANGUAGES
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXTAUTH_URL
ARG SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ENV NEXT_PUBLIC_API_ENDPOINT $NEXT_PUBLIC_API_ENDPOINT
ENV APPLICATION_MODE $APPLICATION_MODE
ENV NEXT_PUBLIC_ADMIN_URL $NEXT_PUBLIC_ADMIN_URL
ENV NEXT_PUBLIC_DEFAULT_LANGUAGE $NEXT_PUBLIC_DEFAULT_LANGUAGE
ENV NEXT_PUBLIC_ENABLE_MULTI_LANG $NEXT_PUBLIC_ENABLE_MULTI_LANG
ENV NEXT_PUBLIC_AVAILABLE_LANGUAGES $NEXT_PUBLIC_AVAILABLE_LANGUAGES
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY $NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXTAUTH_URL $NEXTAUTH_URL
ENV SECRET $SECRET
ENV GOOGLE_CLIENT_ID $GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET $GOOGLE_CLIENT_SECRET
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules

# RUN export NEXT_PUBLIC_API_ENDPOINT=$NEXT_PUBLIC_API_ENDPOINT APPLICATION_MODE=$APPLICATION_MODE NEXT_PUBLIC_ADMIN_URL=$NEXT_PUBLIC_ADMIN_URL NEXT_PUBLIC_DEFAULT_LANGUAGE=$NEXT_PUBLIC_DEFAULT_LANGUAGE NEXT_PUBLIC_ENABLE_MULTI_LANG=$NEXT_PUBLIC_ENABLE_MULTI_LANG NEXT_PUBLIC_AVAILABLE_LANGUAGES=$NEXT_PUBLIC_AVAILABLE_LANGUAGES NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY NEXTAUTH_URL=$NEXTAUTH_URL SECRET=$SECRET GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET && yarn build

RUN export $(cat .env | xargs) && yarn build

FROM node:14-alpine as runner
WORKDIR /app
ENV NODE_ENV production
# If you are using a custom next.config.js file, comment/uncomment this line
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/.env ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY package.json next-env.d.ts next-i18next.config.js \
 next.config.js postcss.config.js tailwind.config.js tsconfig.json vercel.json ./
ENV NEXT_TELEMETRY_DISABLED 1

EXPOSE 3004
CMD ["yarn", "start"]